export const TEMPLATES = {
    'basic_values': [
        'Spirituality',
        'Family',
        'Friends',
        'Significant Other',
        'Health',
        'Learning',
        'Fun',
        'Career',
    ],
    'blank': [],
    'cuisines': [
        'Italian',
        'Mexican',
        'Japanese',
        'Indian',
        'Thai',
        'French',
        'Korean',
        'Chinese',
        'Mediterranean',
        'American',
        'German',
        'Spanish',
    ],
    'detailed_values': [
        'Parents',
        'Siblings',
        'Significant Other',
        'Friends',
        'Spirituality',
        'Health',
        'Learning',
        'Fun',
        'Career',
        'Honesty',
        'Compassion',
        'Discipline',
        'Creativity',
        'Integrity',
        'Kindness',
        'Perseverance',
        'Growth',
    ],
    'funny_situations': [
        'Accidentally sending a text to the wrong person',
    ],
    'love_languages': [
        'Acts of Service',
        'Quality Time',
        'Words of Affirmation',
        'Gifts',
        'Physical Touch',
    ],
    'romantic_gestures': [
        'Breakfast in Bed',
        'Home-cooked Meal',
        'Surprise Event Tickets',
        'Small Thoughtful Gifts',
        'Cuddling',
        'Useful Gifts',
        'Movie Night',
        'Compliments, Love Letter',
        'Weekend Getaway',
        'Candlelight Dinner',
        'Massage/Spa Day',
    ],
};

export type TemplateKey = keyof typeof TEMPLATES;
